[package]
name = "domain"
version = "0.1.0"
authors = ["Antoine BAGNAUD <bagnaud.antoine@gmail.com>"]

[dependencies]
uuid = { version = "0.6", features = ["v4", "serde"] }
serde = "1.0.69"
serde_derive = "1.0.69"
